### ISSUE TITLE
Issue in the infinite scroll

### ISSUE THREAD

**Issue by pradumangoyal** [IMGIITRoorkee/omniport-frontend#28]
**Describe the bug**
The issue is in the way infinite scroll is implemented across the frontend. When the screen is too big, or the content is too small as compared to the screen there isn't a scrollbar which can be scrolled to fetch more content and thus hiding the content. 

**To Reproduce**
Visit the Team members section in any Groups with at least 15-20 members added.

**Expected behavior**
The content should not be hidden

**Screenshots**
`Groups` was the most near to a valid solution, we should have a Load More button at the end whenever more content can be fetched (which is currently present only here) and clicking on that should load the next content (which is not present even here).
![image](https://user-images.githubusercontent.com/34851451/83370604-899ba400-a3dd-11ea-9a35-f5979c049663.png)

**Additional context**
The instances where I can recall such a scroll are as follows:
1. In the feed
2. List of posts in the groups
3. List of team members in the groups.

**Comment by dhruvkb** [comment]
:+1: I agree with this, having a 'Load More' button is generally perceived as good UX, especially as a fallback in cases like this where infinite scroll does not work as expected.

**Comment by Sparsh1212** [comment]
Hey! I would like to work on this issue. Kindly assign this to me.

**Comment by pradumangoyal** [comment]
Please continue

**Comment by Sparsh1212** [comment]
@pradumangoyal can we now close this issue ?
